module.exports = {
  apps: [
    {
      name: "ABC-Drivers",
      script: "./bin/www",
      watch: true,
      ignore_watch: ["node_modules", "public", "logs"],
      env_local: {
        PORT: 4888,
        NODE_ENV: "local",
        DOMAIN_URL: "http://127.0.0.1:4888",
        DB_MONGO_URL: "",
        JWT_SECRET: "jsonwebtoken",
        SMTP_PORT: 587,
        SMTP_HOST: "smtp.gmail.com",
        SMTP_SECURE_CONNECTION: "",
        SMTP_AUTH_USER: "",
        SMTP_AUTH_PASSWORD: "",
        SMTP_SOURCE_EMAIL: "",
      },
      env: {
        PORT: 4888,
        NODE_ENV: "local",
        DOMAIN_URL: "http://127.0.0.1:4888",
        DB_MONGO_URL: "",
        JWT_SECRET: "jsonwebtoken",
        SMTP_PORT: 587,
        SMTP_HOST: "smtp.gmail.com",
        SMTP_SECURE_CONNECTION: "",
        SMTP_AUTH_USER: "",
        SMTP_AUTH_PASSWORD: "",
        SMTP_SOURCE_EMAIL: "",
      },
      env_production: {
        PORT: 4888,
        NODE_ENV: "production",
        DOMAIN_URL: "http://127.0.0.1:4888",
        DB_MONGO_URL: "",
        JWT_SECRET: "jsonwebtoken",
        SMTP_PORT: 587,
        SMTP_HOST: "smtp.gmail.com",
        SMTP_SECURE_CONNECTION: "",
        SMTP_AUTH_USER: "",
        SMTP_AUTH_PASSWORD: "",
        SMTP_SOURCE_EMAIL: "",
      },
      env_staging: {
        PORT: 4888,
        NODE_ENV: "staging",
        DOMAIN_URL: "http://127.0.0.1:4888",
        DB_MONGO_URL: "",
        JWT_SECRET: "jsonwebtoken",
        SMTP_PORT: 587,
        SMTP_HOST: "smtp.gmail.com",
        SMTP_SECURE_CONNECTION: "",
        SMTP_AUTH_USER: "",
        SMTP_AUTH_PASSWORD: "",
        SMTP_SOURCE_EMAIL: "",
      },
    },
  ],
};
